version: '3'
services:
  envoy:
    image: envoyproxy/envoy-dev:943be5375289eba651748901a71cd77686ae06ed
    ports:
      - "9901:9901"
      - "8080:8080"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml